### ISSUE TITLE
HTTP Method & Sending URL for HMAC?

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#10]
In Swagger it mentioned  `HTTP Method` & `Sending URL` has to be the part of the input feed for HMAC function.
 
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/89b4fd90-739d-47ce-8c75-f939406f8078)

`HTTP Method` will always be a `POST` & Sending URL is also mostly a static one for one Vendor.
I don't recall that, if we decided to have `HTTP Method` and `Sending URL` as a part of HMAC.

Appreciate if anybody can clarify this.

**Comment by spedsta** [comment]
Agreed that HTTP Method will always be "POST" for the endpoints defined.
The sending url will be the endpoint url as defined on Swagger. Ie..."/v1/TripRequest"

**Comment by asiridissa** [comment]
So, do we need to keep `HTTP Method` & `Sending URL` as a part of input string, or do we remove these?

**Comment by NomeQ** [comment]
I am completely ambivalent on this. Not sure what we gain from adding them to the input string, but it's also not a problem to do so. I will leave it to anyone else with strong opinions. I suppose the one thing we potentially gain by having the sending URL is verifying that it matches the source URL for the request, but given RideSheet is going to require a proxy to handle endpoints, we actually won't have the sending URL and the source URL for the request necessarily be the same, anyway.

**Comment by asiridissa** [comment]
In our endpoints, we have validation to accept `POST` requests only. If someone sends a `GET` to us they will get error response.
So we don't have any advantage of including `HTTPMethod` in `INPUT_STRING`.

Our endpoints refuse to accepts the request if the body of the request is malformed.
ex: endpoint `/v1/TripStatusChange` only accepts the request with JSON body of the format of `tripStatusChange` in schema.json.
If someone send `tripRequest` JSON to `/v1/TripStatusChange` it will return an error code.
Even if we accept a wrong JSON at our endpoints (because there are some overlapping properties that matches with the expected JSON body), it will fail to pass JSON schema validation with malformed or additional properties in it.
So we don't see any advantage of including `Sending URL` in `INPUT_STRING` as well.

I believe that, not having `HTTPMethod` & `Sending URL` does not affect the process. [Helpful comment](https://github.com/RideNoCo/drt-tds/issues/9#issuecomment-1822047883)
Having these add some workload in both sending and receiving processes.

So I suggest to remove `HTTPMethod` & `Sending URL` from HMAC `INPUT_STRING`.

**Comment by asiridissa** [comment]
Decided to keep both `HTTPMethod` and `Sending URL` in the HMAC input string.
Closing this issue with updating [swagger 0.5.a3](https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.5.a3).
