### ISSUE TITLE
customerReferral.customerReferralId needs to be GUID?

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#20]
It described as '**unique ID from ordering client**' in description.
But the `format` property is not defined as `uuid` for this.
Shall we put `format:"uuid"` for following `customerReferralId ` properties?
 
https://github.com/RideNoCo/drt-tds/blob/066ffa9e1bc96db329ff80a0b013333be7f68170/spec/schema.json#L294-L297
https://github.com/RideNoCo/drt-tds/blob/066ffa9e1bc96db329ff80a0b013333be7f68170/spec/schema.json#L274-L277

**Comment by keviniano** [comment]
`customerReferralId`s are currently coming from one source only, so current usage wouldn't result in ID collisions, but for robustness, I think it would be a good idea to specify these as `uuid`. We're already using GUIDs to generate these IDs anyways.
