### ISSUE TITLE
referralResponseType possible value list not mentioned

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#21]
We don't have the possible list of values for `customerReferralResponse.referralResponseType` mentioned in schema.
Shall we add a possible list?
ex: `"enum": [ "Accepted", "Rejected" ]'

https://github.com/RideNoCo/drt-tds/blob/066ffa9e1bc96db329ff80a0b013333be7f68170/spec/schema.json#L298

**Comment by keviniano** [comment]
I don't think we have these defined yet.

**Comment by keviniano** [comment]
At our meeting on 12/11/23 we decided to use `accept` and `reject` as the two options for the enum.
