### ISSUE TITLE
All phone numbers should be string instead of integer

### ISSUE THREAD

**Issue by steverideschedulercom** [RideNoCo/drt-tds#27]
The spec states that phone numbers are integerNullable but should be stringNullable

https://github.com/RideNoCo/drt-tds/blob/d8e61d64cad7d7dc64d2c2b85758e576c6c3b5c9/spec/schema.json#L330-L331

**Comment by keviniano** [comment]
Consensus at meeting on 1/22/24 was to make this change for all phone numbers.
