### ISSUE TITLE
CustomerId, FirstName, LastName need to be mandatory

### ISSUE THREAD

**Issue by steverideschedulercom** [RideNoCo/drt-tds#28]
In CustomerInfoType, CustomerId, FirstName, LastName need to be mandatory.  Since we need to use these to determine if a client already exists in our system, we need a way to look them up.  Also, a customer without a first and last name doesn't make sense.

https://github.com/RideNoCo/drt-tds/blob/d8e61d64cad7d7dc64d2c2b85758e576c6c3b5c9/spec/schema.json#L325

**Comment by steverideschedulercom** [comment]
![image](https://github.com/RideNoCo/drt-tds/assets/133813553/27be3d86-b6fb-4848-bf82-fc3dfe0ed626)

If there is no birthdate, RideScheduler will use the Creation Date

**Comment by keviniano** [comment]
Consensus at 1-22-24 meeting: CustomerId, FirstName, LastName will be mandatory
