### ISSUE TITLE
Some properties need to be nullable

### ISSUE THREAD

**Issue by steverideschedulercom** [RideNoCo/drt-tds#29]
Some properties need to be nullable including Time properties and Address properties

https://github.com/RideNoCo/drt-tds/blob/d8e61d64cad7d7dc64d2c2b85758e576c6c3b5c9/spec/schema.json#L36-L44

**Comment by keviniano** [comment]
Consensus from 1/22/24 meeting: The times need to be optional even though the trip request will need to have at least one of them completed. Because of the variety of options, they all need to be optional.
