### ISSUE TITLE
addressName should be optional

### ISSUE THREAD

**Issue by NomeQ** [RideNoCo/drt-tds#30]
In the addressType schema, addressName is a required field.

However, many of the addresses will be home addresses, in which case an addressName doesn't make sense.

**Comment by asiridissa** [comment]
we can put the person's name in the `addressName` field for Home addresses

**Comment by keviniano** [comment]
Consensus at 1/22/24 meeting was that `addressName` should be made nullable.

**Comment by asiridissa** [comment]
Swagger updated
https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.6.a1#/addressType
