### ISSUE TITLE
Type needs to be timeNullable for following Time properties.

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#36]
Shall we change the type of following properties `timeNullable` instead of `Time`?

https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L68
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L100
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L111
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L197
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L204
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L236
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L254
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L256

**Comment by keviniano** [comment]
`availabilityForService` seems like it could easily be made nullable. For the others, the times seem like they are essential to the purpose of the message.

Knowing that there's some time pressure here, maybe make these changes in a branch so you can move forward with a version that has these fields as nullable until we have a group conversation?

**Comment by spedsta** [comment]
In the Spedsta implementation, for any optional fields we do not have a preference for the type definition so it can be null, empty string or time. We are by default sending any optional fields in the JSON object as empty string.

**Comment by asiridissa** [comment]
@spedsta empty string for `time` fields are not going to validate against schema.
Now it expects only an object of type `Time`. 
That's why the request to make it to accept either `Time` object or `null`.
https://github.com/RideNoCo/drt-tds/blob/098b1e6e2c9346ee341294cf40cf6dd3d722da34/spec/schema.json#L405-L429

**Comment by spedsta** [comment]
Changes to existing fields that are required to be optional nullable vs our existing implementation of empty string will entail effort to implement and validate.

**Comment by NomeQ** [comment]
Even prior to this change, the spec did not accept an empty string for this field and has been this way for quite some time.

**Comment by asiridissa** [comment]
Yes, schema never allowed empty strings in `Time` type fields. Not even in the previous json schema.
