### ISSUE TITLE
Type needs to be floatNullable for following properties.

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#37]
Shall we change the type of following properties `floatNullable` instead of `integerNullable`?

https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L252
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L257
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L73
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L105
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L142-L143
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L217
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L383-L401

**Comment by keviniano** [comment]
+1

**Comment by spedsta** [comment]
Agreed

**Comment by keviniano** [comment]
I'd like to narrow this issue to make it only about changing integers to floats. The three cases of changing required attributes to nullable ones seem like a separate issue.

This could just be set to zero:
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L252

These seem like they should stay required:
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L142-L143

**Comment by asiridissa** [comment]
Swagger updated.
https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.7.a1

**Comment by keviniano** [comment]
Per meeting on 2/5/24 all attributes will be made floatNullable.
