### ISSUE TITLE
Nullable AddressType properties

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#38]
Shall we make following `AddressType` properties to become new `addressTypeNullable` type? 

https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L69-L71
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L101-L103
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L253
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L255
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L261
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L329
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L332

**Comment by keviniano** [comment]
I think like we definitely need that for `transferPoint`, `address`, and `mailingBillingAddress` at minimum. For the others, I wonder if having the address is essential to the purpose of the message.

As with #36, maybe make these changes in a branch so you can move forward with a version that has these fields as nullable until we have a group conversation?

**Comment by spedsta** [comment]
Same comments as with #36

**Comment by keviniano** [comment]
Per 2/5/24 meeting, all fields of type `AddressType` listed in original issue will be made nullable. Among current implementors, [line 329](https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L329) is required for all current use cases, but the field will be made nullable in anticipation for future participants who may not have rider addresses to share.
