### ISSUE TITLE
PaymentTypeList should be paymentTypeList

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#39]
Property name is in Pascal case. It needs to be in Camel case.
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L72

**Comment by spedsta** [comment]
agreed

**Comment by keviniano** [comment]
+1
I'll take this on and create a PR.

**Comment by asiridissa** [comment]
Swagger updated.
https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.7.a1
