### ISSUE TITLE
CustomerInfoType.tripTicketId needs to allow nulls

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#40]
When CustomerInfoType used in the Referrel message it does not needs the tripTicketId.
Shall we make CustomerInfoType.tripTicketId nullable?
https://github.com/RideNoCo/drt-tds/blob/60895208587337adb34d9359d714780355ad12a4/spec/schema.json#L321-L325

**Comment by spedsta** [comment]
In the Spedsta implementation, this field is empty string. This can be removed from the object or nullable.

**Comment by keviniano** [comment]
I'll create a PR to make it nullable.

**Comment by keviniano** [comment]
Actually, is `tripTicketId` needed under any scenario inside `CustomerInfoType`? When `CustomerInfoType` is used as part of a `tripRequest`, the `tripRequest` already has its own `tripTicketId`. Can it just be removed entirely as Harsh suggests?

**Comment by asiridissa** [comment]
I vote for removing `tripticketId` too.

**Comment by asiridissa** [comment]
Sorry, we need `tripTicketId` for one scenario.
`tripRequest.customerInfo` is not required. 
`customerInfo` can be sent later with `customerInfo.tripTicketId` to link the customer with the `tripRequest`.
So shall we make the `tripTicketId` nullable?

**Comment by keviniano** [comment]
Per meeting 2/5/24, `tripTicketId` will be removed completely. A `customerInfo` object can be associated with a `tripTicketId` by it being embedded in telegrams 1A or 2A, which themselves would have a `tripTicketId`.

**Comment by asiridissa** [comment]
Swagger updated
https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.8
