### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by spedsta** [RideNoCo/drt-tds#46]
There was a previous version of the Swagger API that had an *asterisk next to the required fields under the respective endpoints. 
I do not see the asterisk currently on the endpoints on the latest swagger versions and the schema only has a few required fields.

For example under the schema 
description, I see in the "TripRequest" endpoint only has the "tripTicketId" as required.  Fields such as "pickupAddress" and "dropoffAddress" are not tagged as required.

Are the required fields documented somewhere else? 
We have made assumptions in our implementation on those required fields in the endpoints but would propose to have those documented somewhere for alignment.

**Comment by asiridissa** [comment]
I don't recall about marking addresses as required. 
But I agree that there are some properties we need to mark as required.
@spedsta would you like to suggest the list of properties here?

All the previous swagger versions are there if we want to check.
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/d3d23fa8-cdd8-43ba-80bb-9adce308c52d)

**Comment by spedsta** [comment]
/TripRequest required fields:
pickupAddress
dropoffAddress
pickupTime OR appointmentTime

/ProviderOrderConfirmation required fields:
driverName OR driverId

/CustomerReferral
firstLegalName
lastName
address
phone OR mobilePhone OR emailAddress

**Comment by asiridissa** [comment]
Using `oneOf ` caused to enforce to have only one of the given properties.
Need to use `anyOf` instead.
