### ISSUE TITLE
Logic needed for mobile phone, home phone, email address

### ISSUE THREAD

**Issue by ehamilton7** [RideNoCo/drt-tds#50]
For the customer information, mobile phone, phone or email address (one of those three) must be present for the customer referral to be accepted so we have a way to contact them. I don't think there's a way to add this to the spec but we need the vendors to add this so we have a way to contact the customer. What are your thoughts?

**Comment by asiridissa** [comment]
Found a way to make part of this validation work. 
`customerReferral.customerInfo.phone` is required
and 
`tripRequest.customerInfo.phone` is not required in this example.

https://json-schema.org/understanding-json-schema/reference/conditionals#dependentschemas
https://www.jsonschemavalidator.net/s/Iz1yoSky
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/d2d6b5e6-63c0-436d-a048-1d9210709ffc)

**Comment by asiridissa** [comment]
This could be the final solution.

https://www.jsonschemavalidator.net/s/cLAqFt2C
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/250f26a2-7c16-4c2e-9ef2-4d166ca17fc3)
