### ISSUE TITLE
Phone format

### ISSUE THREAD

**Issue by spedsta** [RideNoCo/drt-tds#55]
Recommend E.164 format for following phone number fields in customerInfo object:
phone
mobilePhone

https://www.twilio.com/docs/glossary/what-e164

**Comment by spedsta** [comment]
Updated swagger with "phone" and "mobilePhone" fields with E.164 example.
Example is:  "+19708009560"

**Comment by asiridissa** [comment]
Please update the schema as well.

**Comment by asiridissa** [comment]
> Updated swagger with "phone" and "mobilePhone" fields with E.164 example. Example is: "+19708009560"

@spedsta , I can not find this change in swagger.
What is the swagger version did you update?

**Comment by asiridissa** [comment]
Swagger updated to https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.11.0 with issue #56 PR.

**Comment by asiridissa** [comment]
Swagger updated https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.14.0
