### ISSUE TITLE
Customer Info Field Types

### ISSUE THREAD

**Issue by NomeQ** [RideNoCo/drt-tds#56]
```
"ethnicity": { "$ref": "#/$defs/booleanNullable" },
"emailAddress": {
    "allOf":[{ "$ref": "#/$defs/stringNullable", "format":"email" }]
},
"veteran": { "$ref": "#/$defs/stringNullable" },
```

It seems like we probably want ethnicity to be either a string or an enum, rather than a boolean.

We also probably want veteran to be a boolean, rather than a string.

**Comment by ehamilton7** [comment]
Decision to make ethnicity an enum.
https://www.census.gov/programs-surveys/decennial-census/decade/2020/planning-management/release/faqs-race-ethnicity.html
Veteran status will be a boolean.

**Comment by asiridissa** [comment]
Changes made `ethnicity` not nullable.
Shall we make `ethnicity` nullable?

**Comment by keviniano** [comment]
Yes, apologies for not keeping it nullable. I can do another PR later today.

**Comment by asiridissa** [comment]
Swagger updated.
https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.12.0
