### ISSUE TITLE
Need to discuss how we determine customer uniqueness

### ISSUE THREAD

**Issue by steverideschedulercom** [RideNoCo/drt-tds#59]
Do we only rely on the customerId?

![image](https://github.com/RideNoCo/drt-tds/assets/133813553/ac12ed4d-4843-4c0a-a60a-8e5f5b526ef1)

**Comment by ehamilton7** [comment]
Decision made to not have a unique ID for the project but to check the individual fields (first, last names, phone number and birthdate) for customer duplication.
