### ISSUE TITLE
`customerContactDate` should not be required

### ISSUE THREAD

**Issue by asiridissa** [RideNoCo/drt-tds#62]
Make the `customerReferral.customerContactDate` not required

**Comment by asiridissa** [comment]
Swagger updated https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.14.0

**Comment by asiridissa** [comment]
'customerContactDate' needs to be nullable too.

**Comment by keviniano** [comment]
Ah, quite right. Sorry to miss that.

**Comment by asiridissa** [comment]
Swagger updated https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.14.0
