### ISSUE TITLE
Lat/Long Float field trailing zeros

### ISSUE THREAD

**Issue by ehamilton7** [RideNoCo/drt-tds#71]
Hi all,
We're having some testing failures due to interpretations of float fields for lat/long with trailing zeros. I did some research on this and it seems like there are some philosophical differences on how this is interpreted and it's not very clear cut. We are also running out of time as we are supposed to go live on Monday. From what it seems to me, there are two options:
1) drop the trailing zeros.
2) change lat/long from a float field to a string field.
What do you all think? Please respond asap.

**Comment by NomeQ** [comment]
1. It's not possible to choose to drop/keep the trailing 0's. This is a matter of programming language used.
2. This should not matter if the *raw message body* is used for HMAC. For example, running any sort of "parse" on the incoming message will change it. Many frameworks will automatically parse an incoming message as the intended type (e.g. JSON) so that would have to be circumvented to get the raw message.
2. I think the lowest maintenance way to handle this would just be to remove the `body` from the HMAC parameters entirely. All our messages will be sent over HTTPS, so we don't need to validate the message integrity, as it already handles that. 
3. We could change all floats to strings. It wouldn't be especially difficult, but I worry at some other point the HMAC signatures won't match due to some other discrepancy in the raw message body vs the parsed message body.

**Comment by ehamilton7** [comment]
Great comments, Nome. This is very helpful and I appreciate it.

We will discuss Nome's bullets on Monday. Others: feel free to weigh in with your thoughts in advance of that call too.

**Comment by keviniano** [comment]
Nome's comments seem spot-on to me. 

Given that 2 of the 3 participating vendors have come up against this issue, I personally lean towards pulling the message body out of the HMAC hash calculation. There's a short-term cost, as it would require a change to everyone's code, but it would ultimately simplify things and prevent this issue from happening down the road with new vendors.

It's important to note that there are valid use cases for including the raw message body in calculating the HMAC signature, particularly when there's a risk of tampering with the message in transit. However, in our specific case, all messages are sent with SSL/TLS encryption, a robust security measure that effectively prevents any tampering.

**Comment by asiridissa** [comment]
We have predicted this situation in very early stages of the design and planning, and took precautions.
#8 
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/a48e8ece-e5cc-4672-99f5-22cf69801447)

**Comment by ehamilton7** [comment]
Unrelated to the HMAC body text issues (those are resolved), it seems to me that different programming languages treat trailing zeros with floats a bit differently. I've done a deep dive down the rabbit hole of float fields and trailing zeros and have learned that, essentially, **you all are right.** None of this is particularly well determined and it seems like there are arguments for and against both sides. This is different from the HMAC body where you have to validate what you're given...even if it means you get an lat/long of platypus/rhino.

For the good of the spec, I do think there is value in us making a decision about fractional trailing zeros in floats. This is not a right vs. wrong...this is just a decision so others don't have to decide themselves (they will be as polarized as we are).

I consulted an expert...their recommendation (acknowledging that all of you are right) was to drop the fractional trailing zeros in floats because the javascript Number object drops trailing zeros. Javascript is what is typically used to interpret json numbers.

Thoughts?

**Comment by ehamilton7** [comment]
So after some phone calls it sounds like there isn't enough consensus on trailing zeros and we've spent so much time on this that I think it is best for us to drop this. Currency will make this even trickier because a 12.50 fare is correct (and has a trailing zero).

Since our HMAC body uses the exact body payload, this really is a non-issue as messages will be able to be exchanged and system interoperate so I'm closing this issue.
![image](https://github.com/RideNoCo/drt-tds/assets/98833553/b8704983-891b-408c-b5a6-f54a220797f9)
![image](https://github.com/RideNoCo/drt-tds/assets/98833553/b8704983-891b-408c-b5a6-f54a220797f9)
