### ISSUE TITLE
Customer information - home address field

### ISSUE THREAD

**Issue by ehamilton7** [RideNoCo/drt-tds#72]
For the customer information telegram, we have the home address field as nullable. I think this should be changed from addressTypeNullable to addressType as the home address is required.
[Line 349](https://github.com/RideNoCo/drt-tds/blob/main/spec/schema.json)

Thoughts?

**Comment by NomeQ** [comment]
Didn't we decide that this was more of a business rule rather than something universally applicable to all agencies? 

I say that just as a philosophical note on the spec. In Callsheet, `address` is already required to send a customer referral, and it will not send until one is entered.

**Comment by ehamilton7** [comment]
During the [Feb. 5](https://docs.google.com/document/d/1XxNOtFuVk_gT3WvMje3xxei7SZkWm7QztgPhUHNTbaE/edit) meeting we decided that for the trip requests and a lot of other fields. I wasn't sure if the customer referral was tied to this code or not. Does line 349 tie to trip requests too? If so, then we should keep it nullable.

For reference, we also did say this at that meeting:
Note: a better longer term solution would be to add a new telegram type that includes the required fields from each agency but this is out of our current scope. Possible future work for us/others.

**Comment by ehamilton7** [comment]
At our June 24 meeting, we discussed the option of making home address required for customer referrals. After Asiri did some research on this, he determined that the level of effort is outside of our budget so this will need to be a future development item.
